version: 2
updates:
  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: "/manager"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 5
