import { image } from "@nextui-org/react";

export const laptop = [
    {
        name: "MacBook Air 13”",
        screen: "13.3-inch Retina display",
        chip: "M1 chip",
        img: ["/img/mac/mba13-midnight-select-202402.jpg"],
        color: [
            {
                name: "Midnight",
                img: "/img/mac/mba13-starlight-select-202402_SW_COLOR.jpg",
                product: ["/img/mac/mba13-starlight-select-202402.jpg"],
                specs: [
                    {
                        ram: "8GB",
                        ssd: "512GB",
                        price: "32.999.000đ hoặc 1.344.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "8GB",
                        ssd: "1TB",
                        price: "37.999.000đ hoặc 1.547.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "8GB",
                        ssd: "2TB",
                        price: "47.999.000đ hoặc 1.954.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "16GB",
                        ssd: "512GB",
                        price: "37.999.000đ hoặc 1.547.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "16GB",
                        ssd: "1TB",
                        price: "42.999.000đ hoặc 1.751.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "16GB",
                        ssd: "2TB",
                        price: "52.999.000đ hoặc 2.158.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "24GB",
                        ssd: "512GB",
                        price: "42.999.000đ hoặc 1.751.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "24GB",
                        ssd: "1TB",
                        price: "47.999.000đ hoặc 1.954.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "24GB",
                        ssd: "2TB",
                        price: "57.999.000đ hoặc 2.362.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                ]
            },
            {
                name: "Starlight",
                img: "/img/mac/mba13-midnight-select-202402_SW_COLOR.jpg",
                product: ["/img/mac/mba13-midnight-select-202402.jpg"],
                specs: [
                    {
                        ram: "8GB",
                        ssd: "512GB",
                        price: "32.999.000đ hoặc 1.344.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "8GB",
                        ssd: "1TB",
                        price: "37.999.000đ hoặc 1.547.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "8GB",
                        ssd: "2TB",
                        price: "47.999.000đ hoặc 1.954.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "16GB",
                        ssd: "512GB",
                        price: "37.999.000đ hoặc 1.547.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "16GB",
                        ssd: "1TB",
                        price: "42.999.000đ hoặc 1.751.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "16GB",
                        ssd: "2TB",
                        price: "52.999.000đ hoặc 2.158.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "24GB",
                        ssd: "512GB",
                        price: "42.999.000đ hoặc 1.751.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "24GB",
                        ssd: "1TB",
                        price: "47.999.000đ hoặc 1.954.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "24GB",
                        ssd: "2TB",
                        price: "57.999.000đ hoặc 2.362.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                ]
            },
            {
                name: "Space Gray",
                img: "/img/mac/mba13-spacegray-select-202402_SW_COLOR.jpg",
                product: ["/img/mac/mba13-spacegray-select-202402.jpg"],
                specs: [
                    {
                        ram: "8GB",
                        ssd: "512GB",
                        price: "32.999.000đ hoặc 1.344.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "8GB",
                        ssd: "1TB",
                        price: "37.999.000đ hoặc 1.547.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "8GB",
                        ssd: "2TB",
                        price: "47.999.000đ hoặc 1.954.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "16GB",
                        ssd: "512GB",
                        price: "37.999.000đ hoặc 1.547.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "16GB",
                        ssd: "1TB",
                        price: "42.999.000đ hoặc 1.751.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "16GB",
                        ssd: "2TB",
                        price: "52.999.000đ hoặc 2.158.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "24GB",
                        ssd: "512GB",
                        price: "42.999.000đ hoặc 1.751.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "24GB",
                        ssd: "1TB",
                        price: "47.999.000đ hoặc 1.954.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "24GB",
                        ssd: "2TB",
                        price: "57.999.000đ hoặc 2.362.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                ]
            },
            {
                name: "Silver",
                img: "/img/mac/mba13-silver-select-202402_SW_COLOR.jpg",
                product: ["/img/mac/mba13-silver-select-202402.jpg"],
                specs: [
                    {
                        ram: "8GB",
                        ssd: "512GB",
                        price: "32.999.000đ hoặc 1.344.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "8GB",
                        ssd: "1TB",
                        price: "37.999.000đ hoặc 1.547.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "8GB",
                        ssd: "2TB",
                        price: "47.999.000đ hoặc 1.954.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "16GB",
                        ssd: "512GB",
                        price: "37.999.000đ hoặc 1.547.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "16GB",
                        ssd: "1TB",
                        price: "42.999.000đ hoặc 1.751.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "16GB",
                        ssd: "2TB",
                        price: "52.999.000đ hoặc 2.158.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "24GB",
                        ssd: "512GB",
                        price: "42.999.000đ hoặc 1.751.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "24GB",
                        ssd: "1TB",
                        price: "47.999.000đ hoặc 1.954.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                    {
                        ram: "24GB",
                        ssd: "2TB",
                        price: "57.999.000đ hoặc 2.362.000đ/tháng mỗi tháng cho 24 tháng",
                        desc: "",
                        connection: "",
                    },
                ]
            },
        ]
    }
]