name: Build swipe application

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Node.js 20.9.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: run lint # will run `yarn test` command
  admin:
    name: build-admin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Node.js 20.9.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
          dir: "./x/admin"

      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: run lint # will run `yarn test` command
          dir: "./x/admin"
