name: Build swipe application

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Node.js 22.0.0
        uses: actions/setup-node@v3
        with:
          node-version: 22.0.0

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
          dir: "client"

      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: run lint # will run `yarn test` command
          dir: "client"

  admin:
    name: build-admin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Node.js 22.0.0
        uses: actions/setup-node@v3
        with:
          node-version: 22.0.0

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
          dir: "manager"

      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: run lint # will run `yarn test` command
          dir: "manager"
